-- ================================================================
-- Grupo Abasto | Importación de Catalogo con Precios 1.xlsx
-- Generado por scripts/generate-catalog-sql.py. No editar a mano.
-- Seguro para reejecutar: enlaza productos equivalentes sin cambiar sus
-- nombre, descripción, categoría ni imagen; después agrega los nuevos sin
-- imagen y elimina los productos fuera de este catálogo.
-- El archivo de origen repite PLA-4060-COR; se importa una única vez por SKU.
-- ================================================================

BEGIN;

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS sku TEXT,
  ADD COLUMN IF NOT EXISTS catalog_category TEXT,
  ADD COLUMN IF NOT EXISTS indicator_codes SMALLINT[] NOT NULL DEFAULT ARRAY[]::SMALLINT[];

CREATE UNIQUE INDEX IF NOT EXISTS products_sku_unique
  ON products (sku)
  WHERE sku IS NOT NULL;

CREATE INDEX IF NOT EXISTS products_indicator_codes_idx
  ON products USING GIN (indicator_codes);

CREATE TABLE IF NOT EXISTS catalog_packaging_prices (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  volume_liters NUMERIC(6,2) NOT NULL,
  price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  currency TEXT NOT NULL DEFAULT 'MXN',
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE catalog_packaging_prices ENABLE ROW LEVEL SECURITY;

INSERT INTO catalog_packaging_prices (id, label, volume_liters, price, currency)
VALUES
  ('envase-1l', 'Envase de 1 L', 1, 5.00, 'MXN'),
  ('envase-5l', 'Envase de 5 L', 5, 15.00, 'MXN'),
  ('envase-20l', 'Envase de 20 L', 20, 45.00, 'MXN')
ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label,
  volume_liters = EXCLUDED.volume_liters,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  updated_at = NOW();

WITH catalog (
  sku,
  name,
  description,
  category,
  catalog_category,
  indicator_codes,
  price,
  image_url,
  legacy_name
) AS (
VALUES
('LIM-CLR-REPUESTO', 'Cloro sin envase SOLO LIQUIDO', 'Presentación según catálogo: Cloro sin envase SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[5]::SMALLINT[], 13.50, '/catalog-images/catalogo-con-precios-1/image1.png', 'Cloro'),
('CLR-PERRO-REPUESTO', 'Cloro de perro sin envase SOLO LIQUIDO', 'Presentación según catálogo: Cloro de perro sin envase SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1]::SMALLINT[], 33.00, '/catalog-images/catalogo-con-precios-1/image1.png', 'Cloro de Perro'),
('PERRO-SHAMPOO', 'Shampoo para perro', 'Presentación según catálogo: Shampoo para perro.', 'limpieza-general', 'Limpieza', ARRAY[1]::SMALLINT[], NULL, NULL, NULL),
('CLR-PAST-KG-LMB', 'Pastillas de cloro para escusado paquete de 1 kilogramo', 'Presentación según catálogo: Pastillas de cloro para escusado paquete de 1 kilogramo.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 180.00, '/catalog-images/catalogo-con-precios-1/image2.png', 'Pastillas Cloro'),
('CLR-PAST-KG-PRG', 'Pastillas de cloro para escusado paquete de 1 kilogramo', 'Presentación según catálogo: Pastillas de cloro para escusado paquete de 1 kilogramo.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 180.00, '/catalog-images/catalogo-con-precios-1/image2.png', NULL),
('LIM-PINRP-REOUESTO', 'Limpiador tipo pinol con repelente SOLO LIQUIDO', 'Presentación según catálogo: Limpiador tipo pinol con repelente SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 19.50, '/catalog-images/catalogo-con-precios-1/image3.png', 'Limpiador tipo Pinol con Repelente'),
('LIM-PINVRD-REOUESTO', 'Limpiador tipo pinol VERDE SOLO LIQUIDO', 'Presentación según catálogo: Limpiador tipo pinol VERDE SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 22.50, '/catalog-images/catalogo-con-precios-1/image3.png', NULL),
('FAB-LV-REPUESTO', 'Fabuloso Lavanda SOLO LIQUIDO', 'Presentación según catálogo: Fabuloso Lavanda SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 10.50, '/catalog-images/catalogo-con-precios-1/image4.png', NULL),
('FAB-LL-REPUESTO', 'Fabuloso Lima limon SOLO LIQUIDO', 'Presentación según catálogo: Fabuloso Lima limon SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 10.50, '/catalog-images/catalogo-con-precios-1/image3.png', 'Limpiador Multiusos Lima Limón'),
('FAB-FRU-REPUESTO', 'Fabuloso Frutal SOLO LIQUIDO', 'Presentación según catálogo: Fabuloso Frutal SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 10.50, '/catalog-images/catalogo-con-precios-1/image3.png', NULL),
('FAB-MRFR-REPUESTO', 'Fabuloso Mar fresco s SOLO LIQUIDO', 'Presentación según catálogo: Fabuloso Mar fresco s SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 10.50, '/catalog-images/catalogo-con-precios-1/image1.png', 'Limpiador Multiusos Mar Fresco'),
('FAB-CAS-REPUESTO', 'Fabuloso CASCADAS SOLO LIQUIDO', 'Presentación según catálogo: Fabuloso CASCADAS SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 10.50, '/catalog-images/catalogo-con-precios-1/image1.png', 'Fabuloso Cascada'),
('FAB-CAMA-RESPUESTO', 'Fabuloso Canela con manzana SOLO LIQUIDO', 'Presentación según catálogo: Fabuloso Canela con manzana SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 10.50, '/catalog-images/catalogo-con-precios-1/image5.png', 'Limpiador Multiusos Canela Manzana'),
('DES-MULTI-RESPUESTO', 'Desengrasante MULTIUSOS SOLO LIQUIDO', 'Presentación según catálogo: Desengrasante MULTIUSOS SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 48.00, '/catalog-images/catalogo-con-precios-1/image6.png', NULL),
('DES-IND-RESPUESTO', 'Desengrasante INDUSTRIAL SOLO LIQUIDO', 'Presentación según catálogo: Desengrasante INDUSTRIAL SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[3, 4, 5]::SMALLINT[], 58.50, '/catalog-images/catalogo-con-precios-1/image6.png', 'Desengrasante Industrial'),
('QUI-COCH-REPUESTO', 'Quita cochambre SOLO LIQUIDO', 'Presentación según catálogo: Quita cochambre SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[3, 4, 5]::SMALLINT[], 75.00, '/catalog-images/catalogo-con-precios-1/image5.png', 'Quitacochambre en Gel'),
('WIN-TIP-REPUESTO', 'Windex SOLO LIQUIDO', 'Presentación según catálogo: Windex SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 15.00, '/catalog-images/catalogo-con-precios-1/image1.png', 'Limpiavidrios'),
('JPM-ALM-RESPUESTO', 'Jabon para manos almendras SOLO LIQUIDO', 'Presentación según catálogo: Jabon para manos almendras SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 31.50, '/catalog-images/catalogo-con-precios-1/image1.png', 'Jabón para Manos'),
('JPM-CC-RESPUESTO', 'Jabon para manos COCO SOLO LIQUIDO', 'Presentación según catálogo: Jabon para manos COCO SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 31.50, '/catalog-images/catalogo-con-precios-1/image1.png', NULL),
('SHOO-AUT-CERA-REPUESTO', 'Shampoo para auto con cera SOLO LIQUIDO', 'Presentación según catálogo: Shampoo para auto con cera SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[4]::SMALLINT[], 45.00, '/catalog-images/catalogo-con-precios-1/image3.png', NULL),
('SHOO-AUT-ESP-REPUESTO', 'Shampoo para auto con espuma SOLO LIQUIDO', 'Presentación según catálogo: Shampoo para auto con espuma SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[4]::SMALLINT[], 45.00, '/catalog-images/catalogo-con-precios-1/image3.png', 'Shampoo para Autos'),
('ARO-AUT-REPUESTO', 'Aroma para auto SOLO LIQUIDO', 'Presentación según catálogo: Aroma para auto SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[4]::SMALLINT[], 45.00, '/catalog-images/catalogo-con-precios-1/image1.png', NULL),
('ABRIL-AUT-REPUESTO', 'Abrillantador blanco para Auto SOLO LIQUIDO', 'Presentación según catálogo: Abrillantador blanco para Auto SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[4]::SMALLINT[], 135.00, '/catalog-images/catalogo-con-precios-1/image7.png', NULL),
('TEFL-AUT-REPUESTO', 'Abrillantador teflonblanco para Auto SOLO LIQUIDO', 'Presentación según catálogo: Abrillantador teflonblanco para Auto SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[4]::SMALLINT[], 255.00, '/catalog-images/catalogo-con-precios-1/image4.png', NULL),
('SUA-MM-REPUESTO', 'Suavizante de ropa tipo Momentos Magicos SOLO LIQUIDO', 'Presentación según catálogo: Suavizante de ropa tipo Momentos Magicos SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[2, 3]::SMALLINT[], 33.00, '/catalog-images/catalogo-con-precios-1/image4.png', 'Suavizante'),
('SUA-DOW-REPUESTO', 'Suavizante de ropa tipo Downy SOLO LIQUIDO', 'Presentación según catálogo: Suavizante de ropa tipo Downy SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[2, 3]::SMALLINT[], 25.50, '/catalog-images/catalogo-con-precios-1/image1.png', 'Suavizante Azul'),
('JPT-DET-REPUESTO', 'Jabon para trastes Detercon REPUESTO', 'Presentación según catálogo: Jabon para trastes Detercon REPUESTO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 48.00, '/catalog-images/catalogo-con-precios-1/image3.png', 'Jabón para Trastes'),
('JPT-SLV-REPUESTO', 'Jabon para trastes LimonREPUESTO', 'Presentación según catálogo: Jabon para trastes LimonREPUESTO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 48.00, '/catalog-images/catalogo-con-precios-1/image3.png', NULL),
('VIN-AUT-REPUESTO', 'Vinil para llantas para Auto SOLO LIQUIDO', 'Presentación según catálogo: Vinil para llantas para Auto SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[4]::SMALLINT[], 170.00, '/catalog-images/catalogo-con-precios-1/image1.png', 'Vinil para Autos'),
('DET+CLR-RESPUESTO', 'Detergente para ropa mas color REPUESTO', 'Presentación según catálogo: Detergente para ropa mas color REPUESTO.', 'limpieza-general', 'Limpieza', ARRAY[2, 3]::SMALLINT[], 31.50, '/catalog-images/catalogo-con-precios-1/image1.png', 'Detergente para Ropa'),
('DET+NGR-RESPUESTO', 'Detergente para ropa mas Negro REPUESTO', 'Presentación según catálogo: Detergente para ropa mas Negro REPUESTO.', 'limpieza-general', 'Limpieza', ARRAY[2, 3]::SMALLINT[], 31.50, '/catalog-images/catalogo-con-precios-1/image8.png', 'Detergente para Ropa Negra'),
('SAN-DES-REPUESTO', 'Sanitizante Desinfectante SOLO LIQUIDO', 'Presentación según catálogo: Sanitizante Desinfectante SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 36.00, '/catalog-images/catalogo-con-precios-1/image1.png', 'Desinfectante'),
('GAL-ANT-REPUESTO', 'Gel Antibacterial SOLO LIQUIDO', 'Presentación según catálogo: Gel Antibacterial SOLO LIQUIDO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 90.00, '/catalog-images/catalogo-con-precios-1/image1.png', NULL),
('QTS-GEL-REPUESTO', 'Quita sarro en gel REPUESTO', 'Presentación según catálogo: Quita sarro en gel REPUESTO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 84.00, '/catalog-images/catalogo-con-precios-1/image6.png', 'Quitasarro en Gel'),
('QTS-LQD-REPUESTO', 'Quita sarro en liquido REPUESTO', 'Presentación según catálogo: Quita sarro en liquido REPUESTO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 31.50, '/catalog-images/catalogo-con-precios-1/image6.png', 'Quitasarro Líquido'),
('VIN-BLC-REPUESTO', 'Vinagre blanco REPUESTO', 'Presentación según catálogo: Vinagre blanco REPUESTO.', 'limpieza-general', 'Limpieza', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 24.00, '/catalog-images/catalogo-con-precios-1/image1.png', NULL),
('TIP-ZOTE-BARRA', 'Jabon en barra tipo ZOTE', 'Presentación según catálogo: Jabon en barra tipo ZOTE.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 90.00, '/catalog-images/catalogo-con-precios-1/image9.png', NULL),
('LIM-BIC-KG', 'Bicarbonato de sodio LEON LIMPIO', 'Presentación según catálogo: Bicarbonato de sodio LEON LIMPIO.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 60.30, '/catalog-images/catalogo-con-precios-1/image10.png', 'Bicarbonato de Sodio'),
('ROM-TIP', 'Jabon en polvo tipo Roma kileado', 'Presentación según catálogo: Jabon en polvo tipo Roma kileado.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 40.00, '/catalog-images/catalogo-con-precios-1/image10.png', NULL),
('ROM-KIL-1KG', 'JABON ROMA KIELADO', 'Presentación según catálogo: JABON ROMA KIELADO.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 50.00, '/catalog-images/catalogo-con-precios-1/image11.png', NULL),
('LIM-ARI-KG', 'Jabon en polvo tipo ariel', 'Presentación según catálogo: Jabon en polvo tipo ariel.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 40.00, '/catalog-images/catalogo-con-precios-1/image12.png', NULL),
('CAJ-BAÑ-PAP-GC', 'Papel de baño rollo 180m GCPAPER 12 PZS', 'Presentación según catálogo: Papel de baño rollo 180m GCPAPER 12 PZS.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 469.33, '/catalog-images/catalogo-con-precios-1/image13.png', NULL),
('BAÑ-PAP-GC', 'Papel de baño rollo 180m GCPAPER', 'Presentación según catálogo: Papel de baño rollo 180m GCPAPER.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 45.00, '/catalog-images/catalogo-con-precios-1/image13.png', 'Papel de Baño Rollo 180m GCPaper'),
('BAÑ-QUA-JB', 'Papel de baño quality paquete de 6', 'Presentación según catálogo: Papel de baño quality paquete de 6.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 65.00, '/catalog-images/catalogo-con-precios-1/image14.png', NULL),
('AERO-ARO-WISE', 'Aromatizante en aerosol olores diferentes marca WISE', 'Presentación según catálogo: Aromatizante en aerosol olores diferentes marca WISE.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], NULL, '/catalog-images/catalogo-con-precios-1/image15.png', NULL),
('TOA-ROL-MRL', 'Toalla de papel en rollo 180 metros Marli', 'Presentación según catálogo: Toalla de papel en rollo 180 metros Marli.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 85.00, '/catalog-images/catalogo-con-precios-1/image16.png', 'Toalla de Papel Rollo 180 metros Marli'),
('TOA-ROL-MOC', 'Toalla en rollo natural MOCAMBO 180 mts', 'Presentación según catálogo: Toalla en rollo natural MOCAMBO 180 mts.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 98.72, '/catalog-images/catalogo-con-precios-1/image17.png', NULL),
('CAJ-TOA-ROL-MOC', 'Toalla en rollo natural MOCAMBO 180 mts', 'Presentación según catálogo: Toalla en rollo natural MOCAMBO 180 mts.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 592.31, '/catalog-images/catalogo-con-precios-1/image17.png', NULL),
('SER-TOA-KIA', 'Servitoalla kihara 160 pzs rollo', 'Presentación según catálogo: Servitoalla kihara 160 pzs rollo.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 26.73, '/catalog-images/catalogo-con-precios-1/image18.png', 'Servitoalla Kihara 160'),
('CAJ-TOA-COT-INT', 'Caja de toallas interdobladas Cottonelle con 6 paquetes', 'Presentación según catálogo: Caja de toallas interdobladas Cottonelle con 6 paquetes.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 648.05, '/catalog-images/catalogo-con-precios-1/image19.png', NULL),
('TOA-COT-INT', 'Toallas interdobladas Cottonelle con 150 unidades', 'Presentación según catálogo: Toallas interdobladas Cottonelle con 150 unidades.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 108.01, '/catalog-images/catalogo-con-precios-1/image19.png', NULL),
('CAJ-TOA-DAL-INT', 'Caja de toallas interdobladas Dalia con 20 paquetes', 'Presentación según catálogo: Caja de toallas interdobladas Dalia con 20 paquetes.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 369.33, '/catalog-images/catalogo-con-precios-1/image20.png', NULL),
('TOA-DAL-INT', 'Toallas interdobladas Dalia con 100 unidades', 'Presentación según catálogo: Toallas interdobladas Dalia con 100 unidades.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 18.47, '/catalog-images/catalogo-con-precios-1/image20.png', NULL),
('CAJ-TOA-SNLX-INT', 'Caja de toallas interdobladas Sanilux con 20 paquetes', 'Presentación según catálogo: Caja de toallas interdobladas Sanilux con 20 paquetes.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 278.68, '/catalog-images/catalogo-con-precios-1/image21.png', NULL),
('TOA-SNLX-INT', 'Toallas interdobladas Sanilux con 100 unidades', 'Presentación según catálogo: Toallas interdobladas Sanilux con 100 unidades.', 'papel', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 13.93, '/catalog-images/catalogo-con-precios-1/image21.png', NULL),
('ESC-CEP-GRND', 'Escoba con cepillo grande de uso normal', 'Presentación según catálogo: Escoba con cepillo grande de uso normal.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 55.38, '/catalog-images/catalogo-con-precios-1/image22.png', NULL),
('ESC-CEP-CH', 'Escoba con cepillo chico de uso normal', 'Presentación según catálogo: Escoba con cepillo chico de uso normal.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 48.46, '/catalog-images/catalogo-con-precios-1/image22.png', 'Escoba Tipo Cepillo Chico'),
('ESC-4-HIL-IND', 'Escoba de 4 hilos tipo bruja Industrial', 'Presentación según catálogo: Escoba de 4 hilos tipo bruja Industrial.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 101.54, '/catalog-images/catalogo-con-precios-1/image23.png', 'Escoba de 4 Hilos Tipo Bruja'),
('ESC-ABA-CEP', 'Escoba cepillo de abanico', 'Presentación según catálogo: Escoba cepillo de abanico.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 55.38, '/catalog-images/catalogo-con-precios-1/image24.png', 'Escoba Cepillo de Abanico'),
('ESC-RUDO-CEP', 'Ecoba uso rudo de cepillo', 'Presentación según catálogo: Ecoba uso rudo de cepillo.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 90.77, '/catalog-images/catalogo-con-precios-1/image25.png', 'Escoba Uso Rudo de Cepillo'),
('CAS-CEP-NUM', 'Cepillo de escoba Castor NUMERO', 'Presentación según catálogo: Cepillo de escoba Castor NUMERO.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 138.46, '/catalog-images/catalogo-con-precios-1/image26.png', 'Cepillo de Castor'),
('MECH-MICR-TEL', 'Mechudo micro tela nnmero 16', 'Presentación según catálogo: Mechudo micro tela nnmero 16.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 127.69, '/catalog-images/catalogo-con-precios-1/image27.png', 'Mechudo de Microfibra Española'),
('MECH-HIL-24-IND', 'Mechudo de hilaza #24 Industrial', 'Presentación según catálogo: Mechudo de hilaza #24 Industrial.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 96.92, '/catalog-images/catalogo-con-precios-1/image28.png', 'Mechudo de Hilaza #24 Industrial'),
('MECH-MICR-TRE', 'Mechudo de microfibra Trenzada', 'Presentación según catálogo: Mechudo de microfibra Trenzada.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 117.78, '/catalog-images/catalogo-con-precios-1/image29.png', 'Mechudo de Microfibra Trenzada'),
('JAL-NEO-75', 'Jalador de neopreono 75 cmt', 'Presentación según catálogo: Jalador de neopreono 75 cmt.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 355.73, '/catalog-images/catalogo-con-precios-1/image30.png', NULL),
('JAL-NEO-75-CAS', 'Jalador de neopreono 75 cmts Castor', 'Presentación según catálogo: Jalador de neopreono 75 cmts Castor.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 368.47, '/catalog-images/catalogo-con-precios-1/image30.png', NULL),
('JAL-JMB-40', 'Jalador Jumbo Economico 40', 'Presentación según catálogo: Jalador Jumbo Economico 40.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 130.77, '/catalog-images/catalogo-con-precios-1/image31.png', NULL),
('REC-CHI-PLAS', 'Recogedor de plastico chico', 'Presentación según catálogo: Recogedor de plastico chico.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 44.62, '/catalog-images/catalogo-con-precios-1/image32.png', 'Recogedor de Plástico Chico'),
('EXT-1.5', 'Extencion de escoba de 1.5 mts', 'Presentación según catálogo: Extencion de escoba de 1.5 mts.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 116.77, '/catalog-images/catalogo-con-precios-1/image33.png', 'Extensión de Escoba 1.5 mts'),
('EXT-1.2-JAL', 'Extencion de Jalador 1.2 mts', 'Presentación según catálogo: Extencion de Jalador 1.2 mts.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 46.15, '/catalog-images/catalogo-con-precios-1/image33.png', NULL),
('GUA-LAT-OVL', 'Guantes de latex de difrentes tallas maraca OVAL', 'Presentación según catálogo: Guantes de latex de difrentes tallas maraca OVAL.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 33.85, '/catalog-images/catalogo-con-precios-1/image34.png', NULL),
('GUA-LAT-SCT', 'Guantes de latex de difrentes tallas maraca SCOTCH', 'Presentación según catálogo: Guantes de latex de difrentes tallas maraca SCOTCH.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 33.85, '/catalog-images/catalogo-con-precios-1/image35.png', NULL),
('FIB-VRD-96', 'Fibra verde de cocina p96', 'Presentación según catálogo: Fibra verde de cocina p96.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 31.54, '/catalog-images/catalogo-con-precios-1/image36.png', NULL),
('ESP-FIB-SCOT-VRD', 'Esponja de cocina SCOTCH con fibra verde', 'Presentación según catálogo: Esponja de cocina SCOTCH con fibra verde.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 26.14, '/catalog-images/catalogo-con-precios-1/image37.png', NULL),
('ESP-FIB-SCOT-AZL', 'Esponja de cocina SCOTCH con fibra Azul', 'Presentación según catálogo: Esponja de cocina SCOTCH con fibra Azul.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 30.77, '/catalog-images/catalogo-con-precios-1/image38.png', NULL),
('TRAP-MRF-AZUL', 'Trapo microfibra azul Membersmark', 'Presentación según catálogo: Trapo microfibra azul Membersmark.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 21.54, '/catalog-images/catalogo-con-precios-1/image39.png', 'Trapo Microfibra Azul Membersmark'),
('CUB-NOR-10L', 'Cubeta forma normal de 1o litros', 'Presentación según catálogo: Cubeta forma normal de 1o litros.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 66.15, '/catalog-images/catalogo-con-precios-1/image40.png', 'Cubeta Forma Normal 10 Litros'),
('PAST-WIESE', 'Pastilla de inodoro Wiese', 'Presentación según catálogo: Pastilla de inodoro Wiese.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 17.69, '/catalog-images/catalogo-con-precios-1/image41.png', 'Pastillas Wise'),
('ATOM-1-ETI', 'Bote de 1 litro con atomizador y etiqueta', 'Presentación según catálogo: Bote de 1 litro con atomizador y etiqueta.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 0.00, NULL, 'Atomizador Plástico'),
('Atom-1-RUD', 'Boet de 1 litro con atomizador rudo', 'Presentación según catálogo: Boet de 1 litro con atomizador rudo.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 45.00, NULL, NULL),
('BOTE-1-ETI', 'Bote de 1 litro con una etiqueta', 'Presentación según catálogo: Bote de 1 litro con una etiqueta.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 0.00, '/catalog-images/catalogo-con-precios-1/image42.png', NULL),
('BOT-5L-E', 'Bote de 5 litos con una etiqueta', 'Presentación según catálogo: Bote de 5 litos con una etiqueta.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 0.00, '/catalog-images/catalogo-con-precios-1/image43.png', 'Bote 5L'),
('BOTE-20L-BDN', 'Bidoon de 20 Litros', 'Presentación según catálogo: Bidoon de 20 Litros.', 'utensilios', 'Jarcería', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 0.00, '/catalog-images/catalogo-con-precios-1/image44.png', 'Bidón 20L'),
('BPC-812-PLY', 'Bolsa de plastico cortada 8X12 (SALSERA)', 'Presentación según catálogo: Bolsa de plastico cortada 8X12 (SALSERA).', 'bolsas', 'Bolsas', ARRAY[3]::SMALLINT[], 87.51, '/catalog-images/catalogo-con-precios-1/image45.png', 'Bolsa de Plástico Cortada 8x12 (Salsera)'),
('BPC-1015-PLY', 'Bolsa de plastico cortada 10X15', 'Presentación según catálogo: Bolsa de plastico cortada 10X15.', 'bolsas', 'Bolsas', ARRAY[3]::SMALLINT[], 87.51, '/catalog-images/catalogo-con-precios-1/image45.png', NULL),
('BPC-1020-POLY', 'Bolsa de plastico cortada 10X20', 'Presentación según catálogo: Bolsa de plastico cortada 10X20.', 'bolsas', 'Bolsas', ARRAY[3]::SMALLINT[], 87.51, '/catalog-images/catalogo-con-precios-1/image45.png', NULL),
('BCA-CMI-1830', 'Bolsa Mini poliseda color con asa 18x30', 'Presentación según catálogo: Bolsa Mini poliseda color con asa 18x30.', 'bolsas', 'Bolsas', ARRAY[3]::SMALLINT[], 90.35, '/catalog-images/catalogo-con-precios-1/image46.png', NULL),
('BCA-CCH-2540', 'Bolsa Chica poliseda color con asa 25x40', 'Presentación según catálogo: Bolsa Chica poliseda color con asa 25x40.', 'bolsas', 'Bolsas', ARRAY[3]::SMALLINT[], 86.08, '/catalog-images/catalogo-con-precios-1/image47.png', 'Bolsa de Plástico con Asa'),
('BCA-CME-2550', 'Bolsa Mediana poliseda color con asa 25x50', 'Presentación según catálogo: Bolsa Mediana poliseda color con asa 25x50.', 'bolsas', 'Bolsas', ARRAY[3]::SMALLINT[], 86.08, '/catalog-images/catalogo-con-precios-1/image48.png', NULL),
('BCA-CGR-3060', 'Bolsa Grande poliseda color con asa 30x60', 'Presentación según catálogo: Bolsa Grande poliseda color con asa 30x60.', 'bolsas', 'Bolsas', ARRAY[3]::SMALLINT[], 86.08, '/catalog-images/catalogo-con-precios-1/image49.png', NULL),
('BCA-NMI-1830', 'Bolsa Mini polipapel negra con asa 18x30', 'Presentación según catálogo: Bolsa Mini polipapel negra con asa 18x30.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 72.48, '/catalog-images/catalogo-con-precios-1/image50.png', NULL),
('BCA-NCH-2540', 'Bolsa Chica polipapel negra con asa 25x40', 'Presentación según catálogo: Bolsa Chica polipapel negra con asa 25x40.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 70.45, '/catalog-images/catalogo-con-precios-1/image51.png', NULL),
('BCA-NME-2550', 'Bolsa Mediana polipapel negra con asa 25x50', 'Presentación según catálogo: Bolsa Mediana polipapel negra con asa 25x50.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 70.45, '/catalog-images/catalogo-con-precios-1/image51.png', NULL),
('BCA-NGR-3060', 'Bolsa Grande polipapel negra con asa 30x60', 'Presentación según catálogo: Bolsa Grande polipapel negra con asa 30x60.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 70.45, '/catalog-images/catalogo-con-precios-1/image51.png', NULL),
('BCA-NJU-4590', 'Bolsa Jumbo polipapel negra con asa 45x90', 'Presentación según catálogo: Bolsa Jumbo polipapel negra con asa 45x90.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 70.45, '/catalog-images/catalogo-con-precios-1/image51.png', 'Bolsa Negra Jumbo'),
('BBA-5070-NGA', 'Bolsa de basura 50x70 Negra', 'Presentación según catálogo: Bolsa de basura 50x70 Negra.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 48.98, '/catalog-images/catalogo-con-precios-1/image52.png', NULL),
('BBA-5070-TRAS', 'Bolsa de basura 50x70 Transparente', 'Presentación según catálogo: Bolsa de basura 50x70 Transparente.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 120.48, '/catalog-images/catalogo-con-precios-1/image53.png', NULL),
('BBA-6090', 'Bolsa de basura 60x90 ALEX', 'Presentación según catálogo: Bolsa de basura 60x90 ALEX.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 48.98, '/catalog-images/catalogo-con-precios-1/image54.png', 'Bolsa Polipel 60x90'),
('BBA-90120', 'Bolsa de basura 90x120 ALEX', 'Presentación según catálogo: Bolsa de basura 90x120 ALEX.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 48.98, '/catalog-images/catalogo-con-precios-1/image54.png', 'Bolsa Polipel 90x120'),
('ROL-POL-1525', 'Bolsa en rollo 15x25 POLISEDA', 'Presentación según catálogo: Bolsa en rollo 15x25 POLISEDA.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 63.70, '/catalog-images/catalogo-con-precios-1/image55.png', 'Bolsa en Rollo 15x25 Poliseda'),
('ROL-POL-2030', 'Bolsa en rollo 20x30 POLISEDA', 'Presentación según catálogo: Bolsa en rollo 20x30 POLISEDA.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 63.70, '/catalog-images/catalogo-con-precios-1/image55.png', 'Bolsa en Rollo 20x30 Poliseda'),
('ROL-POL-2535', 'Bolsa en rollo 25x35 POLISEDA', 'Presentación según catálogo: Bolsa en rollo 25x35 POLISEDA.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 63.70, '/catalog-images/catalogo-con-precios-1/image55.png', 'Bolsa en Rollo 25x35 Poliseda'),
('ROL-POL-3040', 'Bolsa en rollo 30x40 POLISEDA', 'Presentación según catálogo: Bolsa en rollo 30x40 POLISEDA.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 63.70, '/catalog-images/catalogo-con-precios-1/image55.png', 'Bolsa en Rollo 30x40 Poliseda'),
('ROL-POLY-1525', 'Bolsa de poliseda en rollo 15x25 ply', 'Presentación según catálogo: Bolsa de poliseda en rollo 15x25 ply.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 83.83, '/catalog-images/catalogo-con-precios-1/image55.png', NULL),
('ROL-POLY-2030', 'Bolsa de poliseda en rollo 20x30 ply', 'Presentación según catálogo: Bolsa de poliseda en rollo 20x30 ply.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 83.83, '/catalog-images/catalogo-con-precios-1/image55.png', NULL),
('ROL-POLY-2535', 'Bolsa de poliseda en rollo 25x35 ply', 'Presentación según catálogo: Bolsa de poliseda en rollo 25x35 ply.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 83.83, '/catalog-images/catalogo-con-precios-1/image55.png', NULL),
('ROL-POLY-3040', 'Bolsa de poliseda en rollo 30x40 ply', 'Presentación según catálogo: Bolsa de poliseda en rollo 30x40 ply.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 83.83, '/catalog-images/catalogo-con-precios-1/image55.png', NULL),
('POLY-3545-PLA', 'Bolsa en rollo 35x45 POLYBAG PLASTICO', 'Presentación según catálogo: Bolsa en rollo 35x45 POLYBAG PLASTICO.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.98, '/catalog-images/catalogo-con-precios-1/image56.png', NULL),
('ROL-PLA-1525', 'Bolsa en rollo 15x25 PLASTICO', 'Presentación según catálogo: Bolsa en rollo 15x25 PLASTICO.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.97, '/catalog-images/catalogo-con-precios-1/image56.png', 'Bolsa en Rollo 15x25 Plástico'),
('ROL-PLA-2030', 'Bolsa en rollo 20x30 PLASTICO', 'Presentación según catálogo: Bolsa en rollo 20x30 PLASTICO.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.98, '/catalog-images/catalogo-con-precios-1/image56.png', 'Bolsa en Rollo 20x30'),
('ROL-PLA-2535', 'Bolsa en rollo 25x35 PLASTICO', 'Presentación según catálogo: Bolsa en rollo 25x35 PLASTICO.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.97, '/catalog-images/catalogo-con-precios-1/image56.png', 'Bolsa en Rollo 25x35'),
('ROL-PLA-3040', 'Bolsa en rollo 30x40 PLASTICO', 'Presentación según catálogo: Bolsa en rollo 30x40 PLASTICO.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.98, '/catalog-images/catalogo-con-precios-1/image56.png', 'Bolsa en Rollo 30x40'),
('ROL-LAM-2030', 'Bolsa en rollo de lamina 20x30', 'Presentación según catálogo: Bolsa en rollo de lamina 20x30.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 87.58, '/catalog-images/catalogo-con-precios-1/image55.png', 'Bolsa en Rollo de Lámina 20x30'),
('ROL-LAM-2535', 'Bolsa en rollo de lamina 25x35', 'Presentación según catálogo: Bolsa en rollo de lamina 25x35.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 87.58, '/catalog-images/catalogo-con-precios-1/image55.png', NULL),
('COR-PLA-1525', 'Bolsa en rollo 15x25 POLISEDA cortada', 'Presentación según catálogo: Bolsa en rollo 15x25 POLISEDA cortada.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.97, '/catalog-images/catalogo-con-precios-1/image45.png', NULL),
('COR-PLA-2030', 'Bolsa en rollo 20x30 POLISEDA cortada', 'Presentación según catálogo: Bolsa en rollo 20x30 POLISEDA cortada.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.97, '/catalog-images/catalogo-con-precios-1/image45.png', NULL),
('COR-PLA-2535', 'Bolsa en rollo 25x35 POLISEDA cortada', 'Presentación según catálogo: Bolsa en rollo 25x35 POLISEDA cortada.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.97, '/catalog-images/catalogo-con-precios-1/image45.png', NULL),
('COR-PLA-3040', 'Bolsa en rollo 30x40 POLISEDA cortada', 'Presentación según catálogo: Bolsa en rollo 30x40 POLISEDA cortada.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.97, '/catalog-images/catalogo-con-precios-1/image45.png', NULL),
('PLA-4060-COR', 'Bolsa cortada plastico transparente 40x60', 'Presentación según catálogo: Bolsa cortada plastico transparente 40x60.', 'bolsas', 'Bolsas', ARRAY[1, 2, 3]::SMALLINT[], 76.97, '/catalog-images/catalogo-con-precios-1/image45.png', NULL),
('EMP-GRA-ALI', 'Emplaye de grado alimneticio', 'Presentación según catálogo: Emplaye de grado alimneticio.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 0.00, '/catalog-images/catalogo-con-precios-1/image57.png', 'Rollo de Emplaye 1° Grado Alimenticio'),
('BOB-36-MTS', 'Bobina negra reciclada de 3 a 6 metros JOSE LUIS', 'Presentación según catálogo: Bobina negra reciclada de 3 a 6 metros JOSE LUIS.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 62.46, '/catalog-images/catalogo-con-precios-1/image58.png', NULL),
('EMP-18-C70', 'Rollo de emplaye 18x 70x1000', 'Presentación según catálogo: Rollo de emplaye 18x 70x1000.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 182.93, '/catalog-images/catalogo-con-precios-1/image59.png', NULL),
('EMP-18-C60', 'Rollo de emplaye 18x60x1000', 'Presentación según catálogo: Rollo de emplaye 18x60x1000.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 67.77, '/catalog-images/catalogo-con-precios-1/image59.png', 'Rollo de Emplaye 18 pulgadas Calibre 60'),
('EMQ-FLJ-NGR', 'Fleje negro 1/2', 'Presentación según catálogo: Fleje negro 1/2.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 60.00, '/catalog-images/catalogo-con-precios-1/image60.png', 'Fleje Negro'),
('GRP-FLJ-1/2', 'Grapas para fleje de 1/2', 'Presentación según catálogo: Grapas para fleje de 1/2.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 600.00, '/catalog-images/catalogo-con-precios-1/image61.png', NULL),
('FJRA-MAN-TRSK', 'Flejadora manual traspack', 'Presentación según catálogo: Flejadora manual traspack.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 2400.00, '/catalog-images/catalogo-con-precios-1/image62.png', NULL),
('FJRA-PNZ-MAN-TRSK', 'Flejadora manual traspack con pinzas', 'Presentación según catálogo: Flejadora manual traspack con pinzas.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 3601.33, '/catalog-images/catalogo-con-precios-1/image63.png', 'Flejadora Manual Traspack con Pinzas'),
('SEG-GUA-CAR', 'Guantes dee seguridad de carnza EN PARES', 'Presentación según catálogo: Guantes dee seguridad de carnza EN PARES.', 'desechables', 'Empaque y desechables', ARRAY[5]::SMALLINT[], 58.00, '/catalog-images/catalogo-con-precios-1/image64.png', 'Guantes de Seguridad de Carnaza'),
('CAJ-PIZ-3535', 'Caja de pizza lisa 35*35', 'Presentación según catálogo: Caja de pizza lisa 35*35.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], NULL, '/catalog-images/catalogo-con-precios-1/image91.png', NULL),
('CAJ-PIZ-ESP', 'Caja de pizza lisa de medida especial', 'Presentación según catálogo: Caja de pizza lisa de medida especial.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], NULL, '/catalog-images/catalogo-con-precios-1/image91.png', NULL),
('DES-SER-500PZ-PER', 'Servilletas paquete 500 pzas Persa Colibri', 'Presentación según catálogo: Servilletas paquete 500 pzas Persa Colibri.', 'papel', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 35.41, '/catalog-images/catalogo-con-precios-1/image65.png', 'Servilletas Paquete 500 pzas Colibrí Persa'),
('DES-SER-450PZ', 'Servilletas paquete de 450 Marli pzs', 'Presentación según catálogo: Servilletas paquete de 450 Marli pzs.', 'papel', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 36.76, '/catalog-images/catalogo-con-precios-1/image66.png', 'Servilletas Paquete 450 Marli Abejita'),
('DES-SER-250M', 'Servilletas 1x1 Marlil de 250', 'Presentación según catálogo: Servilletas 1x1 Marlil de 250.', 'papel', 'Empaque y desechables', ARRAY[2]::SMALLINT[], 27.21, '/catalog-images/catalogo-con-precios-1/image67.png', 'Servilletas 1x1 Marli 250'),
('DES-SER-200C', 'Servilletas alta calidad PQT 200 piezas persa', 'Presentación según catálogo: Servilletas alta calidad PQT 200 piezas persa.', 'papel', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 70.58, '/catalog-images/catalogo-con-precios-1/image68.png', NULL),
('DES-CUCH-1K', 'Cucharas paquete de 1 kilo', 'Presentación según catálogo: Cucharas paquete de 1 kilo.', 'desechables', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 64.71, '/catalog-images/catalogo-con-precios-1/image69.png', 'Cucharas'),
('DES-TEN-1K', 'Tenedores paquete 1 kilo', 'Presentación según catálogo: Tenedores paquete 1 kilo.', 'desechables', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 64.71, '/catalog-images/catalogo-con-precios-1/image70.png', 'Tenedores'),
('DES-POP-KG', 'Popote desechable economico', 'Presentación según catálogo: Popote desechable economico.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 79.68, '/catalog-images/catalogo-con-precios-1/image71.png', 'Popote Desechable Económico'),
('MAN-AJE-RYB', 'Papel mantel rojo y blanco 1000 piezas', 'Presentación según catálogo: Papel mantel rojo y blanco 1000 piezas.', 'papel', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 441.18, '/catalog-images/catalogo-con-precios-1/image72.png', 'Papel Mantel Rojo y Blanco 1000 piezas'),
('ALU-GRU-400', 'Papel aluminio calibre Grueso 400', 'Presentación según catálogo: Papel aluminio calibre Grueso 400.', 'papel', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 172.06, '/catalog-images/catalogo-con-precios-1/image73.png', 'Aluminio 400'),
('ALU-C11-1K', 'Papel aluminio calibre 11 1 kilo', 'Presentación según catálogo: Papel aluminio calibre 11 1 kilo.', 'papel', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 141.44, '/catalog-images/catalogo-con-precios-1/image73.png', NULL),
('CHA-007-REY', 'Charola de unicel reyma 007 paquete de 50U', 'Presentación según catálogo: Charola de unicel reyma 007 paquete de 50U.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 69.56, '/catalog-images/catalogo-con-precios-1/image74.png', 'Charola Chica'),
('CHA-CHI-066-REY', 'Charolas de unicel 066 paquete de 50 piezas', 'Presentación según catálogo: Charolas de unicel 066 paquete de 50 piezas.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 32.25, '/catalog-images/catalogo-con-precios-1/image75.png', 'Charola 066'),
('DES-CHA-TAQ', 'Charolas de unicel taquera reyma paquete de 50 pzs', 'Presentación según catálogo: Charolas de unicel taquera reyma paquete de 50 pzs.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 38.50, '/catalog-images/catalogo-con-precios-1/image76.png', 'Charola Chica Reyma'),
('CHA-GRA-855', 'Charolas de unicel 855 paquete de 50 pzs Reyma', 'Presentación según catálogo: Charolas de unicel 855 paquete de 50 pzs Reyma.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 24.12, '/catalog-images/catalogo-con-precios-1/image77.png', NULL),
('CHA-MEGA-1014', 'Charola de unicel muy grande 1014 PQT (10PZ)', 'Presentación según catálogo: Charola de unicel muy grande 1014 PQT (10PZ).', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 36.18, '/catalog-images/catalogo-con-precios-1/image78.png', 'Charola de Unicel Muy Grande PQT 10 pzas'),
('DES-CHA-ELO', 'Charola elotera reyma 50pzs', 'Presentación según catálogo: Charola elotera reyma 50pzs.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 40.74, '/catalog-images/catalogo-con-precios-1/image79.png', 'Charola Elotera'),
('DES-CON-HAM', 'Contenedor unicel de hamburguesa 25 pzas EL REY', 'Presentación según catálogo: Contenedor unicel de hamburguesa 25 pzas EL REY.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 31.18, '/catalog-images/catalogo-con-precios-1/image80.png', 'Charola Hamburguesa'),
('DES-PLA-5EY', 'Plato del 5 100 PZ', 'Presentación según catálogo: Plato del 5 100 PZ.', 'desechables', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 227.94, '/catalog-images/catalogo-con-precios-1/image81.png', NULL),
('DES-CON-77L', 'Contenedor de unicel liso 7x7 unicel 50 PZS Reyma', 'Presentación según catálogo: Contenedor de unicel liso 7x7 unicel 50 PZS Reyma.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 145.12, '/catalog-images/catalogo-con-precios-1/image82.png', 'Contenedor 7x7'),
('DES-CON-88L', 'Contenedor liso 8x8 unicel 50PZS REYMA', 'Presentación según catálogo: Contenedor liso 8x8 unicel 50PZS REYMA.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 136.40, '/catalog-images/catalogo-con-precios-1/image83.png', 'Contenedor 8x8'),
('DES-CON-99LB', 'CONTENEDOR DE UNICEL LISO 9x9 UNICEL BIO 50 PIEZAS', 'Presentación según catálogo: CONTENEDOR DE UNICEL LISO 9x9 UNICEL BIO 50 PIEZAS.', 'desechables', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 183.09, '/catalog-images/catalogo-con-precios-1/image84.png', NULL),
('VAS-16OZ-DART', 'Vaso plastico de 16 OZ Dart paquete de 50 pzs', 'Presentación según catálogo: Vaso plastico de 16 OZ Dart paquete de 50 pzs.', 'vasos', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 94.63, '/catalog-images/catalogo-con-precios-1/image85.png', NULL),
('TAP-BOQ-DART', 'Tapa transparente 16 oz con boquilla paquete de 100 pzs', 'Presentación según catálogo: Tapa transparente 16 oz con boquilla paquete de 100 pzs.', 'vasos', 'Empaque y desechables', ARRAY[2, 3]::SMALLINT[], 140.00, '/catalog-images/catalogo-con-precios-1/image86.png', NULL),
('VAS-12OZ-CAF', 'Vaso de 12 oz para café papelcarton paquete de 50pzs DART', 'Presentación según catálogo: Vaso de 12 oz para café papelcarton paquete de 50pzs DART.', 'vasos', 'Empaque y desechables', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 73.24, '/catalog-images/catalogo-con-precios-1/image87.png', 'Vaso de 12 oz para Café'),
('TAP-NEG-CAF-12', 'Tapa negra de café 12 oz paquete de 100pzs DART', 'Presentación según catálogo: Tapa negra de café 12 oz paquete de 100pzs DART.', 'vasos', 'Empaque y desechables', ARRAY[1, 2, 3, 4, 5]::SMALLINT[], 98.38, '/catalog-images/catalogo-con-precios-1/image88.png', 'Tapa de 12 oz para Café'),
('UNI-VAS-1L', 'Vaso termico de unicel de 1 litros (15pz) Marca Dart', 'Presentación según catálogo: Vaso termico de unicel de 1 litros (15pz) Marca Dart.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 30.66, '/catalog-images/catalogo-con-precios-1/image89.png', NULL),
('UNI-VAS-1/2L', 'Vaso termico de unicel de 1/2 litros (25pz)Marca Dart', 'Presentación según catálogo: Vaso termico de unicel de 1/2 litros (25pz)Marca Dart.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 32.17, '/catalog-images/catalogo-con-precios-1/image90.png', NULL),
('UNI-VAS-TAP-TER', 'Tapa de unicel para vaso termico paquete (50pz)', 'Presentación según catálogo: Tapa de unicel para vaso termico paquete (50pz).', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 79.26, NULL, NULL),
('UNI-VAS-8OZ', 'Vaso termico de unicel 8 OZ paquete 25 pzas', 'Presentación según catálogo: Vaso termico de unicel 8 OZ paquete 25 pzas.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 13.05, NULL, NULL),
('UNI-VAS-10OZ', 'Vaso termico de unicel 10 OZ paquete de 25 PZS', 'Presentación según catálogo: Vaso termico de unicel 10 OZ paquete de 25 PZS.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 14.52, NULL, NULL),
('UNI-VAS-6OZ', 'Vaso termico de unicel 6 OZ paquete de 25 PZS', 'Presentación según catálogo: Vaso termico de unicel 6 OZ paquete de 25 PZS.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 11.80, NULL, NULL),
('UNI-VAS-12OZ', 'Vaso termico de unicel 12 OZ paquete de 25 PZS', 'Presentación según catálogo: Vaso termico de unicel 12 OZ paquete de 25 PZS.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 18.01, NULL, NULL),
('PLA-0-VAS', 'Vaso de plastico del cero El primo paquete de 100 pzs', 'Presentación según catálogo: Vaso de plastico del cero El primo paquete de 100 pzs.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 22.79, NULL, 'Vaso del Cero'),
('PLA-0-TAP', 'Tapa de plastico del cero El primo paquete de 50 pzs', 'Presentación según catálogo: Tapa de plastico del cero El primo paquete de 50 pzs.', 'vasos', 'Empaque y desechables', ARRAY[3]::SMALLINT[], 8.75, NULL, 'Tapa del Cero')
),
linked_legacy_products AS (
  UPDATE products AS product
  SET
    sku = catalog.sku,
    catalog_category = catalog.catalog_category,
    indicator_codes = catalog.indicator_codes,
    price = COALESCE(catalog.price, product.price),
    image_url = COALESCE(NULLIF(product.image_url, ''), catalog.image_url),
    is_active = true
  FROM catalog
  WHERE catalog.legacy_name IS NOT NULL
    AND (product.name = catalog.legacy_name OR product.sku = catalog.sku)
    AND (product.sku IS NULL OR product.sku = catalog.sku)
  RETURNING catalog.sku
)
INSERT INTO products (
  sku,
  name,
  description,
  category,
  catalog_category,
  indicator_codes,
  price,
  image_url,
  is_active
)
SELECT
  catalog.sku,
  catalog.name,
  catalog.description,
  catalog.category,
  catalog.catalog_category,
  catalog.indicator_codes,
  catalog.price,
  catalog.image_url,
  true
FROM catalog
WHERE NOT EXISTS (
  SELECT 1
  FROM linked_legacy_products
  WHERE linked_legacy_products.sku = catalog.sku
)
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name,
  description = COALESCE(NULLIF(products.description, ''), EXCLUDED.description),
  category = EXCLUDED.category,
  catalog_category = EXCLUDED.catalog_category,
  indicator_codes = EXCLUDED.indicator_codes,
  price = COALESCE(EXCLUDED.price, products.price),
  image_url = COALESCE(NULLIF(products.image_url, ''), EXCLUDED.image_url),
  is_active = true;

WITH imported_skus (sku) AS (
VALUES
('LIM-CLR-REPUESTO'),
('CLR-PERRO-REPUESTO'),
('PERRO-SHAMPOO'),
('CLR-PAST-KG-LMB'),
('CLR-PAST-KG-PRG'),
('LIM-PINRP-REOUESTO'),
('LIM-PINVRD-REOUESTO'),
('FAB-LV-REPUESTO'),
('FAB-LL-REPUESTO'),
('FAB-FRU-REPUESTO'),
('FAB-MRFR-REPUESTO'),
('FAB-CAS-REPUESTO'),
('FAB-CAMA-RESPUESTO'),
('DES-MULTI-RESPUESTO'),
('DES-IND-RESPUESTO'),
('QUI-COCH-REPUESTO'),
('WIN-TIP-REPUESTO'),
('JPM-ALM-RESPUESTO'),
('JPM-CC-RESPUESTO'),
('SHOO-AUT-CERA-REPUESTO'),
('SHOO-AUT-ESP-REPUESTO'),
('ARO-AUT-REPUESTO'),
('ABRIL-AUT-REPUESTO'),
('TEFL-AUT-REPUESTO'),
('SUA-MM-REPUESTO'),
('SUA-DOW-REPUESTO'),
('JPT-DET-REPUESTO'),
('JPT-SLV-REPUESTO'),
('VIN-AUT-REPUESTO'),
('DET+CLR-RESPUESTO'),
('DET+NGR-RESPUESTO'),
('SAN-DES-REPUESTO'),
('GAL-ANT-REPUESTO'),
('QTS-GEL-REPUESTO'),
('QTS-LQD-REPUESTO'),
('VIN-BLC-REPUESTO'),
('TIP-ZOTE-BARRA'),
('LIM-BIC-KG'),
('ROM-TIP'),
('ROM-KIL-1KG'),
('LIM-ARI-KG'),
('CAJ-BAÑ-PAP-GC'),
('BAÑ-PAP-GC'),
('BAÑ-QUA-JB'),
('AERO-ARO-WISE'),
('TOA-ROL-MRL'),
('TOA-ROL-MOC'),
('CAJ-TOA-ROL-MOC'),
('SER-TOA-KIA'),
('CAJ-TOA-COT-INT'),
('TOA-COT-INT'),
('CAJ-TOA-DAL-INT'),
('TOA-DAL-INT'),
('CAJ-TOA-SNLX-INT'),
('TOA-SNLX-INT'),
('ESC-CEP-GRND'),
('ESC-CEP-CH'),
('ESC-4-HIL-IND'),
('ESC-ABA-CEP'),
('ESC-RUDO-CEP'),
('CAS-CEP-NUM'),
('MECH-MICR-TEL'),
('MECH-HIL-24-IND'),
('MECH-MICR-TRE'),
('JAL-NEO-75'),
('JAL-NEO-75-CAS'),
('JAL-JMB-40'),
('REC-CHI-PLAS'),
('EXT-1.5'),
('EXT-1.2-JAL'),
('GUA-LAT-OVL'),
('GUA-LAT-SCT'),
('FIB-VRD-96'),
('ESP-FIB-SCOT-VRD'),
('ESP-FIB-SCOT-AZL'),
('TRAP-MRF-AZUL'),
('CUB-NOR-10L'),
('PAST-WIESE'),
('ATOM-1-ETI'),
('Atom-1-RUD'),
('BOTE-1-ETI'),
('BOT-5L-E'),
('BOTE-20L-BDN'),
('BPC-812-PLY'),
('BPC-1015-PLY'),
('BPC-1020-POLY'),
('BCA-CMI-1830'),
('BCA-CCH-2540'),
('BCA-CME-2550'),
('BCA-CGR-3060'),
('BCA-NMI-1830'),
('BCA-NCH-2540'),
('BCA-NME-2550'),
('BCA-NGR-3060'),
('BCA-NJU-4590'),
('BBA-5070-NGA'),
('BBA-5070-TRAS'),
('BBA-6090'),
('BBA-90120'),
('ROL-POL-1525'),
('ROL-POL-2030'),
('ROL-POL-2535'),
('ROL-POL-3040'),
('ROL-POLY-1525'),
('ROL-POLY-2030'),
('ROL-POLY-2535'),
('ROL-POLY-3040'),
('POLY-3545-PLA'),
('ROL-PLA-1525'),
('ROL-PLA-2030'),
('ROL-PLA-2535'),
('ROL-PLA-3040'),
('ROL-LAM-2030'),
('ROL-LAM-2535'),
('COR-PLA-1525'),
('COR-PLA-2030'),
('COR-PLA-2535'),
('COR-PLA-3040'),
('PLA-4060-COR'),
('EMP-GRA-ALI'),
('BOB-36-MTS'),
('EMP-18-C70'),
('EMP-18-C60'),
('EMQ-FLJ-NGR'),
('GRP-FLJ-1/2'),
('FJRA-MAN-TRSK'),
('FJRA-PNZ-MAN-TRSK'),
('SEG-GUA-CAR'),
('CAJ-PIZ-3535'),
('CAJ-PIZ-ESP'),
('DES-SER-500PZ-PER'),
('DES-SER-450PZ'),
('DES-SER-250M'),
('DES-SER-200C'),
('DES-CUCH-1K'),
('DES-TEN-1K'),
('DES-POP-KG'),
('MAN-AJE-RYB'),
('ALU-GRU-400'),
('ALU-C11-1K'),
('CHA-007-REY'),
('CHA-CHI-066-REY'),
('DES-CHA-TAQ'),
('CHA-GRA-855'),
('CHA-MEGA-1014'),
('DES-CHA-ELO'),
('DES-CON-HAM'),
('DES-PLA-5EY'),
('DES-CON-77L'),
('DES-CON-88L'),
('DES-CON-99LB'),
('VAS-16OZ-DART'),
('TAP-BOQ-DART'),
('VAS-12OZ-CAF'),
('TAP-NEG-CAF-12'),
('UNI-VAS-1L'),
('UNI-VAS-1/2L'),
('UNI-VAS-TAP-TER'),
('UNI-VAS-8OZ'),
('UNI-VAS-10OZ'),
('UNI-VAS-6OZ'),
('UNI-VAS-12OZ'),
('PLA-0-VAS'),
('PLA-0-TAP')
)
DELETE FROM products AS product
WHERE NOT EXISTS (
  SELECT 1
  FROM imported_skus
  WHERE imported_skus.sku = product.sku
);

COMMIT;
